Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823972): Gdk-CRITICAL **: 08:46:58.539: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824460): Gdk-CRITICAL **: 08:47:00.644: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824902): Gdk-CRITICAL **: 08:47:00.930: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823237): Gdk-CRITICAL **: 08:47:00.955: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824322): Gdk-CRITICAL **: 08:47:01.014: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825100): Gdk-CRITICAL **: 08:47:01.172: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824858): Gdk-CRITICAL **: 08:47:01.192: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824606): Gdk-CRITICAL **: 08:47:01.233: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824050): Gdk-CRITICAL **: 08:47:01.244: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824442): Gdk-CRITICAL **: 08:47:01.341: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824868): Gdk-CRITICAL **: 08:47:01.288: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824889): Gdk-CRITICAL **: 08:47:01.389: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825212): Gdk-CRITICAL **: 08:47:01.630: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823530): Gdk-CRITICAL **: 08:47:01.764: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824622): Gdk-CRITICAL **: 08:47:02.965: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823536): Gdk-CRITICAL **: 08:47:03.042: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823560): Gdk-CRITICAL **: 08:47:05.894: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823727): Gdk-CRITICAL **: 08:47:06.309: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823632): Gdk-CRITICAL **: 08:47:06.912: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824466): Gdk-CRITICAL **: 08:47:06.929: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823944): Gdk-CRITICAL **: 08:47:07.133: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825204): Gdk-CRITICAL **: 08:47:14.855: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823963): Gdk-CRITICAL **: 08:47:15.192: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824942): Gdk-CRITICAL **: 08:47:15.204: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824744): Gdk-CRITICAL **: 08:47:15.212: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825146): Gdk-CRITICAL **: 08:47:15.216: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823231): Gdk-CRITICAL **: 08:47:15.220: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824794): Gdk-CRITICAL **: 08:47:15.224: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825199): Gdk-CRITICAL **: 08:47:15.228: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824315): Gdk-CRITICAL **: 08:47:15.236: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823662): Gdk-CRITICAL **: 08:47:15.244: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823601): Gdk-CRITICAL **: 08:47:15.248: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825047): Gdk-CRITICAL **: 08:47:15.268: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824296): Gdk-CRITICAL **: 08:47:15.298: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824866): Gdk-CRITICAL **: 08:47:15.312: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824700): Gdk-CRITICAL **: 08:47:15.321: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824912): Gdk-CRITICAL **: 08:47:15.360: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823538): Gdk-CRITICAL **: 08:47:15.362: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824690): Gdk-CRITICAL **: 08:47:15.372: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824006): Gdk-CRITICAL **: 08:47:15.380: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824078): Gdk-CRITICAL **: 08:47:15.404: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824035): Gdk-CRITICAL **: 08:47:15.416: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825022): Gdk-CRITICAL **: 08:47:15.420: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825066): Gdk-CRITICAL **: 08:47:15.432: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823480): Gdk-CRITICAL **: 08:47:15.436: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824099): Gdk-CRITICAL **: 08:47:15.444: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824112): Gdk-CRITICAL **: 08:47:15.452: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823534): Gdk-CRITICAL **: 08:47:15.456: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823693): Gdk-CRITICAL **: 08:47:15.460: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824278): Gdk-CRITICAL **: 08:47:15.468: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824432): Gdk-CRITICAL **: 08:47:15.472: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823853): Gdk-CRITICAL **: 08:47:15.476: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824357): Gdk-CRITICAL **: 08:47:15.480: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824476): Gdk-CRITICAL **: 08:47:15.484: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823990): Gdk-CRITICAL **: 08:47:15.492: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823882): Gdk-CRITICAL **: 08:47:15.494: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824454): Gdk-CRITICAL **: 08:47:15.497: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823247): Gdk-CRITICAL **: 08:47:15.506: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824115): Gdk-CRITICAL **: 08:47:15.528: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825160): Gdk-CRITICAL **: 08:47:15.540: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824332): Gdk-CRITICAL **: 08:47:15.548: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824482): Gdk-CRITICAL **: 08:47:15.552: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823934): Gdk-CRITICAL **: 08:47:15.556: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824675): Gdk-CRITICAL **: 08:47:15.562: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823919): Gdk-CRITICAL **: 08:47:15.575: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824264): Gdk-CRITICAL **: 08:47:15.579: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824256): Gdk-CRITICAL **: 08:47:15.618: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823809): Gdk-CRITICAL **: 08:47:15.645: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3823776): Gdk-CRITICAL **: 08:47:15.652: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824931): Gdk-CRITICAL **: 08:47:15.657: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824286): Gdk-CRITICAL **: 08:47:15.668: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824088): Gdk-CRITICAL **: 08:47:15.677: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823824): Gdk-CRITICAL **: 08:47:15.681: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824909): Gdk-CRITICAL **: 08:47:15.689: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825073): Gdk-CRITICAL **: 08:47:15.693: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825068): Gdk-CRITICAL **: 08:47:15.701: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824639): Gdk-CRITICAL **: 08:47:15.709: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825150): Gdk-CRITICAL **: 08:47:15.713: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824500): Gdk-CRITICAL **: 08:47:15.721: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824310): Gdk-CRITICAL **: 08:47:15.725: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3823233): Gdk-CRITICAL **: 08:47:15.729: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823955): Gdk-CRITICAL **: 08:47:15.737: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3823903): Gdk-CRITICAL **: 08:47:15.741: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824670): Gdk-CRITICAL **: 08:47:15.752: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823528): Gdk-CRITICAL **: 08:47:15.777: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3823754): Gdk-CRITICAL **: 08:47:15.781: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824529): Gdk-CRITICAL **: 08:47:15.785: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824214): Gdk-CRITICAL **: 08:47:15.789: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825054): Gdk-CRITICAL **: 08:47:15.797: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3823790): Gdk-CRITICAL **: 08:47:15.817: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3823525): Gdk-CRITICAL **: 08:47:15.821: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824627): Gdk-CRITICAL **: 08:47:15.832: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825206): Gdk-CRITICAL **: 08:47:15.837: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824452): Gdk-CRITICAL **: 08:47:15.902: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3825208): Gdk-CRITICAL **: 08:47:15.908: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824164): Gdk-CRITICAL **: 08:47:15.914: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825034): Gdk-CRITICAL **: 08:47:15.921: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823532): Gdk-CRITICAL **: 08:47:15.929: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824063): Gdk-CRITICAL **: 08:47:15.937: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823555): Gdk-CRITICAL **: 08:47:15.990: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[1735 9404]
.
[1734 9405]
....
[1725 9436]
.....
[9390 1780]
.......
[1741 9424]
..........
[1690 9442]
.......
[9511 1432]
.............
[9583 1229]
.
[1927 9186]
.......
[9666  947]
...
[9365 1636]
....
[8865 2172]
..
[2554 8436]
.
[9557 1298]
.
[9531 1154]
.
[9302 1458]
..
[9453 1233]
.
[9273 1478]
..
[9415 1435]
.
[9223 1639]
.
[9632 1085]
..
[9634 1037]
.
[9591 1000]
.
[9520 1293]
..
[2667 8310]
.
[9336 1330]
.
[9495 1235]
.
[9677  990]
.
[9304 1456]
.
[2560 8384]
.
[9517 1074]
.
[8547 2248]
.
[2510 8481]
.
[9676  960]
.
[9668  982]
.
[8399 2398]
.
[3181 7759]
.
[9080 1592]
.
[9089 1546]
..
[8790 1948]
.
[7094 3936]
.
[8956 1696]
.
[9047 1500]
.
[3246 7655]
.
[6653 4335]
.
[3180 7720]
.
[7962 2936]
.
[3465 7434]
..
[8162 2601]
.
[7871 2983]
.
[3633 7271]
.
[3859 7034]
..
[8281 2426]
.
[7587 3306]
...
[6044 4856]
.
[8399 2321]
...
[7809 2930]
.
[3715 7143]
.
[4472 6460]
...
[5952 4981]
.
[4806 6137]
.
[6128 4681]
..
[3747 7093]
....
[5784 5116]
.
[5253 5617]
..
[5498 5387]
..........
[5858 4981]
.........
[6125 4661]
..
[5880 4929]
.
[4688 6142]
.
[7366 3263]
.
[5981 4716]
.
[6537 4180]
..
[6240 4514]
.........
[4908 5819]
.........................................................................................................................................................................................................
Data Dump...
.
Data Dump...
...
Data Dump...
.........
Data Dump...
..
Data Dump...
....
Data Dump...
..
Data Dump...
.......
Data Dump...
....................
Data Dump...
.....................
Data Dump...
...
Data Dump...
..........................................................................................................................................................................................
[4468   30]
...................
[4245    9]
.
[4373    8]
.....................
[4065   13]
.
[ 159 4068]
.........
[4249   14]
...
[4003   90]
.........
[4068   23]
.
[3941   26]
....
[3948   11]
.
[3813   16]
..............
[3802   60]
...
[3636   43]
....
[3812   18]
................
[3576   39]
..
[3680   31]
......
[3658   84]
.
[3693   51]
......................
[3395   53]
...
[3360  284]
....
[3349   25]
.
[3391   43]
...
[ 375 3324]
....
[3345   46]
.........
[3193  188]
......
[3340   91]
.......
[ 354 3265]
..
[ 346 3390]
...
[3018  246]
.......
[ 350 3288]
..............
[3124  181]
.
[ 644 2743]
..........
[3148  136]
........
[2915  315]
.........
[ 648 2659]
...
[ 617 2877]
...
[2842  461]
...
[2798  293]
..
[ 592 2743]
....
[2751  474]
........
[ 799 2555]
.
[2230 1145]
...
[2578  614]
..
[ 929 2206]
......
[1946 1323]
...........
[1683 1462]
.......
[ 742 2516]
.......
[ 829 2311]
.
[1057 2195]
.
[1041 2222]
......
[1995  987]
.....
[1331 1826]
..
[2657  282]
..
[1593 1657]
.......
[1722 1385]
.....
[1558 1556]
.....
[2204  675]
...
[1776 1259]
..
[1941  876]
.
[1973  958]
.............
[1759 1230]
....
[1290 1778]
...
[2002  933]
.........
[1444 1442]
....................................................................................................................................
[270  15]
................................................
[233   6]
....
[237   6]
............................
[ 53 296]
.
[205   8]
..............................
[235  10]
........
[218  28]
.
Data Dump...
....
[199  13]
.....
[233   6]
......
[192   7]
.
[207   5]
...................
[211  11]
......................
[205  20]
......
Data Dump...
...
Data Dump...
..........
[181   6]
..........
[183  10]
....
[183   6]
...
Data Dump...
............
[213  22]
..
Data Dump...
....
[191  18]
......................
Data Dump...
............
Data Dump...
.....
[ 80 240]
...
[198  14]
.
Data Dump...
.
Data Dump...

[180   6]
.
[174   7]
...
Data Dump...
....
[193  52]
......
[189   8]
..
Data Dump...
....
[ 60 253]
....
[189  31]
..
[ 62 287]
...............
[159  28]
.
Data Dump...
.......
[169  16]
.....
Data Dump...
..............
[ 94 181]
.....
[ 70 237]
...
Data Dump...
.............
Data Dump...
....
Data Dump...

[176  20]
.................
Data Dump...
.....
[154  39]
..
[ 77 248]
...
Data Dump...
...
[ 65 169]
....
[165  22]
.............
[105 200]
.
[153  15]
.
[ 65 151]
.....
[167  53]
.
Data Dump...
.
Data Dump...
.
[155  66]
....
[140 159]
..
[106 109]
.
[163  71]
........
Data Dump...
.
[118 149]
....
Data Dump...
...
Data Dump...
...
[134 158]
.
Data Dump...
..
Data Dump...
..
Data Dump...

Data Dump...
........
[ 76 189]
...........
[ 98 197]
.
[138 160]
..
Data Dump...
.
[125 171]
..
[ 91 167]
.....
Data Dump...
.
[129  73]
....
[ 76 153]
.
[127  99]
....
Data Dump...

Data Dump...
..
[137  19]
...............
[110 109]
.....
[122  93]
..
[141  34]
.
Data Dump...
.
[126  54]
.....
[123  62]
.....
Data Dump...
.....
[116  93]
.....
Data Dump...

Data Dump...
.........
Data Dump...
.
[104 112]
.....
[93 70]
....
Data Dump...

[135  43]
......
Data Dump...
.
Data Dump...

Data Dump...

Data Dump...
...
Data Dump...
.
Data Dump...
.
Data Dump...
..
Data Dump...

Data Dump...
.................
Data Dump...

Data Dump...
...
Data Dump...
.
Data Dump...

Data Dump...
.......
Data Dump...

Data Dump...
....
Data Dump...

Data Dump...
....
Data Dump...
.
Data Dump...
.
Data Dump...
.
Data Dump...
.
Data Dump...

Data Dump...
...
Data Dump...

Data Dump...

Data Dump...
No 1 3
Done
slurmstepd-phcompute025: error: Detected 19 oom-kill event(s) in StepId=824558.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.
