Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825028): Gdk-CRITICAL **: 08:46:58.055: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823407): Gdk-CRITICAL **: 08:46:58.878: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823945): Gdk-CRITICAL **: 08:47:00.340: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824971): Gdk-CRITICAL **: 08:47:00.454: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824335): Gdk-CRITICAL **: 08:47:00.474: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823333): Gdk-CRITICAL **: 08:47:00.477: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823556): Gdk-CRITICAL **: 08:47:00.658: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825144): Gdk-CRITICAL **: 08:47:01.013: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823730): Gdk-CRITICAL **: 08:47:01.128: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824851): Gdk-CRITICAL **: 08:47:01.155: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825003): Gdk-CRITICAL **: 08:47:01.498: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824762): Gdk-CRITICAL **: 08:47:14.056: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823697): Gdk-CRITICAL **: 08:47:14.338: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825121): Gdk-CRITICAL **: 08:47:14.412: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824738): Gdk-CRITICAL **: 08:47:14.440: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824191): Gdk-CRITICAL **: 08:47:14.500: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824262): Gdk-CRITICAL **: 08:47:14.516: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824506): Gdk-CRITICAL **: 08:47:14.520: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823581): Gdk-CRITICAL **: 08:47:14.528: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823648): Gdk-CRITICAL **: 08:47:14.544: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824792): Gdk-CRITICAL **: 08:47:14.548: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824927): Gdk-CRITICAL **: 08:47:14.552: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824804): Gdk-CRITICAL **: 08:47:14.556: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824136): Gdk-CRITICAL **: 08:47:14.564: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824212): Gdk-CRITICAL **: 08:47:14.568: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824569): Gdk-CRITICAL **: 08:47:14.572: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825009): Gdk-CRITICAL **: 08:47:14.604: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823356): Gdk-CRITICAL **: 08:47:14.623: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823478): Gdk-CRITICAL **: 08:47:14.627: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824224): Gdk-CRITICAL **: 08:47:14.631: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825080): Gdk-CRITICAL **: 08:47:14.634: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824385): Gdk-CRITICAL **: 08:47:14.643: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823822): Gdk-CRITICAL **: 08:47:14.646: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823489): Gdk-CRITICAL **: 08:47:14.650: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824624): Gdk-CRITICAL **: 08:47:14.655: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823772): Gdk-CRITICAL **: 08:47:14.658: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823311): Gdk-CRITICAL **: 08:47:14.662: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824957): Gdk-CRITICAL **: 08:47:14.666: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824025): Gdk-CRITICAL **: 08:47:14.670: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823640): Gdk-CRITICAL **: 08:47:14.674: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823627): Gdk-CRITICAL **: 08:47:14.678: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824513): Gdk-CRITICAL **: 08:47:14.682: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823343): Gdk-CRITICAL **: 08:47:14.686: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823989): Gdk-CRITICAL **: 08:47:14.690: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825191): Gdk-CRITICAL **: 08:47:14.694: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824732): Gdk-CRITICAL **: 08:47:14.698: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823382): Gdk-CRITICAL **: 08:47:14.701: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823973): Gdk-CRITICAL **: 08:47:14.706: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824434): Gdk-CRITICAL **: 08:47:14.710: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824412): Gdk-CRITICAL **: 08:47:14.714: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824710): Gdk-CRITICAL **: 08:47:14.718: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824014): Gdk-CRITICAL **: 08:47:14.722: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824396): Gdk-CRITICAL **: 08:47:14.731: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824594): Gdk-CRITICAL **: 08:47:14.735: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825133): Gdk-CRITICAL **: 08:47:14.743: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824097): Gdk-CRITICAL **: 08:47:14.747: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824943): Gdk-CRITICAL **: 08:47:14.755: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825186): Gdk-CRITICAL **: 08:47:14.759: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824111): Gdk-CRITICAL **: 08:47:14.762: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824430): Gdk-CRITICAL **: 08:47:14.766: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823322): Gdk-CRITICAL **: 08:47:14.769: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823827): Gdk-CRITICAL **: 08:47:14.779: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824162): Gdk-CRITICAL **: 08:47:14.795: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825209): Gdk-CRITICAL **: 08:47:14.803: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824180): Gdk-CRITICAL **: 08:47:14.805: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824551): Gdk-CRITICAL **: 08:47:14.812: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823520): Gdk-CRITICAL **: 08:47:14.820: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823304): Gdk-CRITICAL **: 08:47:14.824: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823369): Gdk-CRITICAL **: 08:47:14.827: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823932): Gdk-CRITICAL **: 08:47:14.831: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824364): Gdk-CRITICAL **: 08:47:14.835: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825179): Gdk-CRITICAL **: 08:47:14.839: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824655): Gdk-CRITICAL **: 08:47:14.856: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824669): Gdk-CRITICAL **: 08:47:14.859: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823962): Gdk-CRITICAL **: 08:47:14.861: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824847): Gdk-CRITICAL **: 08:47:14.864: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824815): Gdk-CRITICAL **: 08:47:14.870: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825225): Gdk-CRITICAL **: 08:47:14.874: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3825163): Gdk-CRITICAL **: 08:47:14.876: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3825151): Gdk-CRITICAL **: 08:47:14.880: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824752): Gdk-CRITICAL **: 08:47:14.887: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823503): Gdk-CRITICAL **: 08:47:14.890: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3823394): Gdk-CRITICAL **: 08:47:14.896: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824464): Gdk-CRITICAL **: 08:47:14.900: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823677): Gdk-CRITICAL **: 08:47:14.905: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824344): Gdk-CRITICAL **: 08:47:14.914: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824298): Gdk-CRITICAL **: 08:47:14.927: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824865): Gdk-CRITICAL **: 08:47:14.931: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3823892): Gdk-CRITICAL **: 08:47:14.932: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825159): Gdk-CRITICAL **: 08:47:14.954: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823913): Gdk-CRITICAL **: 08:47:14.974: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824981): Gdk-CRITICAL **: 08:47:14.978: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823858): Gdk-CRITICAL **: 08:47:14.982: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823611): Gdk-CRITICAL **: 08:47:14.994: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824449): Gdk-CRITICAL **: 08:47:15.010: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824996): Gdk-CRITICAL **: 08:47:15.014: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3823760): Gdk-CRITICAL **: 08:47:15.040: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823596): Gdk-CRITICAL **: 08:47:15.069: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824059): Gdk-CRITICAL **: 08:47:15.160: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824600): Gdk-CRITICAL **: 08:47:15.200: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
..Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[9589 1874]
....
[9609 1871]
....
[9556 1905]
....
[9596 1817]
.
[1727 9609]
..........
[1726 9597]
..
[1693 9644]
...
[1739 9648]
..
[1744 9620]
......................
[2408 8774]
.......
[9307 1995]
....
[9722 1222]
.
[9746 1119]
.
[9738 1071]
....
[9758 1095]
..
[9359 1811]
.
[2222 9014]
.
[9537 1627]
..
[2281 8933]
..
[9562 1536]
..
[9251 1940]
....
[9060 2034]
...
[9154 1789]
.
[9706 1132]
.
[9721 1043]
.
[8892 2042]
.
[9411 1493]
.
[8505 2505]
.
[9350 1499]
.
[8904 2074]
.
[9639 1209]
.
[9643 1186]
.
[2932 8147]
.
[9172 1770]
.
[9413 1253]
.
[9245 1619]
.
[7933 3115]
.
[8814 2101]
.
[9367 1509]
.
[9774  958]
.
[8904 1960]
.
[8470 2437]
.
[9659 1044]
.
[3389 7658]
.
[9773 1070]
.
[9022 1767]
.
[8650 2201]
.
[8872 1939]
..
[3542 7477]
......
[7736 3201]
.
[7906 2946]
.
[8359 2472]
.
[8230 2556]
..
[7478 3487]
..
[7267 3760]
.
[8355 2445]
............
[7126 3742]
.
[7851 2888]
..
[6009 4917]
.
[7284 3562]
.
[5720 5312]
...
[4294 6589]
..
[7625 3172]
.
[7147 3749]
.
[4645 6247]
.
[4242 6739]
.
[6555 4378]
.
[6360 4575]
.
[5754 5207]
.
[5248 5673]
.....
[6803 4066]
............
[5245 5575]
..
[6050 4818]
................
[5974 4823]
.....................................................................................................................................................................................
Data Dump...
.....
Data Dump...
........
Data Dump...
..........
Data Dump...
...
Data Dump...
....
Data Dump...
.
Data Dump...
..
Data Dump...
....
Data Dump...
..................
Data Dump...
.
Data Dump...
.....
Data Dump...
....
Data Dump...
...................................................................................................................................................................
[5591    2]
.......................................
[5335   11]
.....................................
[4502   14]
.............
[4386   64]
.....
[4294  128]
....
[4433   10]
..........
[4310   20]
.......
[4247   33]
..
[4007  157]
..
[3862  299]
.
[4258   13]
.....................
[3823    9]
....
[3828   51]
.
[ 282 3864]
...
[3874   56]
..
[ 275 3931]
.
[ 291 3753]
....
[3727  242]
.....
[3909   55]
.
[3687   61]
.
[3738   89]
.....
[3659  232]
.
[3722   97]
.......
[3521  155]
........
[3490  186]
.......
[3490  158]
...
[3225  347]
...
[3595   72]
...
[3500  137]
.......
[3320  152]
.
[3502   94]
...........
[ 524 3111]
...
[3224  295]
...........
[3102  232]
.....
[3166  201]
..
[3220  142]
.
[2941  586]
...
[ 663 2993]
.
[ 597 3035]
.......
[2893  369]
..................
[2747  568]
......
[2974  203]
...
[2615  722]
.......
[2452  910]
.....
[2557  602]
.......
[2819  331]
....
[2646  544]
........
[1039 2212]
.....
[2468  705]
.
[2164 1034]
..
[1764 1415]
.
[1282 1842]
...........
[1596 1622]
.
[2053 1134]
...
[ 960 2557]
..
[2228  965]
.......
[1506 1887]
..
[1723 1530]
..........
[1913 1139]
......
[1702 1212]
...........
[2028  923]
........................................................................................................
[332   2]
.......................................................................
[344   7]
...........................................................
[248   8]
...............................
Data Dump...
.
[241  24]
............
[221  40]
......
[250   7]
.........
[204   8]
.......
[204  39]
.......
[246  13]
........
[203  84]
.....
[241   3]
........................
[ 59 322]
.
[ 73 340]
..
[225   2]
....
[198  12]
...
[ 72 282]
...........
Data Dump...
.
[199   9]
.........
[241  23]
...
[203  48]
.
[221  14]
.....
[218  28]
..
[225  19]
.............
[219  42]
.........
[205  14]
............
[190  37]
..........
[197  42]
....
[195  26]
..............
Data Dump...
......
[193  20]
.
[ 75 202]
.......
[184  24]
.....
[174  12]
....
[199  11]
.......
Data Dump...

[168  27]
.................
[ 92 266]
........
Data Dump...
..
[159  27]
....
[169  25]
..
[ 71 257]
..
[174  77]
......
Data Dump...
.......
[194  23]
.
Data Dump...

[164  38]
...............
Data Dump...
.......
Data Dump...
....
Data Dump...

[169  70]
.
Data Dump...
...
[164  22]
.........
[179  74]
.................
[152  50]
.
Data Dump...

Data Dump...
....
[135 114]
........
Data Dump...

Data Dump...

Data Dump...
.............
[146  26]
.
[151  46]
...
[100 152]
..
[112 103]
.....
Data Dump...
.
[102 136]
....
Data Dump...
....
Data Dump...

Data Dump...

[145  86]
.
Data Dump...
......
[ 94 114]
.
Data Dump...
.....
Data Dump...

[150  83]
..
[138  65]
...
Data Dump...
...
[142  90]
.....
[116 234]
....
[101 224]
......
Data Dump...

[121 128]
........
Data Dump...
..
Data Dump...
.....
[140  65]
.
[127  55]
.....
Data Dump...
........
Data Dump...
......
Data Dump...
.....
Data Dump...
..
[137  46]
..
Data Dump...
.....
Data Dump...

Data Dump...
............
Data Dump...
.
Data Dump...

Data Dump...
.......
Data Dump...
........
Data Dump...

Data Dump...
...............
Data Dump...
..
Data Dump...
....
Data Dump...
.........
Data Dump...
.
Data Dump...
.............
Data Dump...

Data Dump...
...
Data Dump...

Data Dump...
.
Data Dump...
........
Data Dump...
...
Data Dump...
.
Data Dump...

Data Dump...
.
Data Dump...

Data Dump...

Data Dump...
....
Data Dump...
...
Data Dump...

Data Dump...
.
Data Dump...
No 1 2
Done
slurmstepd-phcompute025: error: Detected 17 oom-kill event(s) in StepId=824557.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.
