Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823626): Gdk-CRITICAL **: 08:46:58.299: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825038): Gdk-CRITICAL **: 08:46:58.589: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823799): Gdk-CRITICAL **: 08:46:58.797: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825161): Gdk-CRITICAL **: 08:47:00.284: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824229): Gdk-CRITICAL **: 08:47:00.379: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824689): Gdk-CRITICAL **: 08:47:00.481: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825090): Gdk-CRITICAL **: 08:47:00.586: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824416): Gdk-CRITICAL **: 08:47:00.641: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823639): Gdk-CRITICAL **: 08:47:01.074: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824788): Gdk-CRITICAL **: 08:47:01.251: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823488): Gdk-CRITICAL **: 08:47:01.998: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824082): Gdk-CRITICAL **: 08:47:02.070: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824269): Gdk-CRITICAL **: 08:47:15.024: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823582): Gdk-CRITICAL **: 08:47:15.167: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824205): Gdk-CRITICAL **: 08:47:15.172: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823742): Gdk-CRITICAL **: 08:47:15.176: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824523): Gdk-CRITICAL **: 08:47:15.179: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823368): Gdk-CRITICAL **: 08:47:15.184: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823765): Gdk-CRITICAL **: 08:47:15.187: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824044): Gdk-CRITICAL **: 08:47:15.192: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825099): Gdk-CRITICAL **: 08:47:15.198: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823523): Gdk-CRITICAL **: 08:47:15.204: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824107): Gdk-CRITICAL **: 08:47:15.208: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823504): Gdk-CRITICAL **: 08:47:15.212: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824411): Gdk-CRITICAL **: 08:47:15.216: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824884): Gdk-CRITICAL **: 08:47:15.224: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824746): Gdk-CRITICAL **: 08:47:15.228: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824648): Gdk-CRITICAL **: 08:47:15.232: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823647): Gdk-CRITICAL **: 08:47:15.240: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823396): Gdk-CRITICAL **: 08:47:15.248: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824947): Gdk-CRITICAL **: 08:47:15.252: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824376): Gdk-CRITICAL **: 08:47:15.256: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824242): Gdk-CRITICAL **: 08:47:15.260: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824817): Gdk-CRITICAL **: 08:47:15.264: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823707): Gdk-CRITICAL **: 08:47:15.268: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823943): Gdk-CRITICAL **: 08:47:15.276: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825134): Gdk-CRITICAL **: 08:47:15.293: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824121): Gdk-CRITICAL **: 08:47:15.300: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823595): Gdk-CRITICAL **: 08:47:15.306: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824663): Gdk-CRITICAL **: 08:47:15.316: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823421): Gdk-CRITICAL **: 08:47:15.320: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824304): Gdk-CRITICAL **: 08:47:15.324: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824533): Gdk-CRITICAL **: 08:47:15.328: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823823): Gdk-CRITICAL **: 08:47:15.332: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823971): Gdk-CRITICAL **: 08:47:15.336: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825184): Gdk-CRITICAL **: 08:47:15.344: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823313): Gdk-CRITICAL **: 08:47:15.356: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824342): Gdk-CRITICAL **: 08:47:15.360: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823551): Gdk-CRITICAL **: 08:47:15.372: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825007): Gdk-CRITICAL **: 08:47:15.376: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825141): Gdk-CRITICAL **: 08:47:15.380: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824221): Gdk-CRITICAL **: 08:47:15.384: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824968): Gdk-CRITICAL **: 08:47:15.387: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824955): Gdk-CRITICAL **: 08:47:15.392: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823342): Gdk-CRITICAL **: 08:47:15.396: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825171): Gdk-CRITICAL **: 08:47:15.400: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824574): Gdk-CRITICAL **: 08:47:15.404: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824935): Gdk-CRITICAL **: 08:47:15.408: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824979): Gdk-CRITICAL **: 08:47:15.412: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823843): Gdk-CRITICAL **: 08:47:15.424: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825166): Gdk-CRITICAL **: 08:47:15.428: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824720): Gdk-CRITICAL **: 08:47:15.432: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823332): Gdk-CRITICAL **: 08:47:15.436: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824000): Gdk-CRITICAL **: 08:47:15.444: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824150): Gdk-CRITICAL **: 08:47:15.448: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825108): Gdk-CRITICAL **: 08:47:15.452: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823323): Gdk-CRITICAL **: 08:47:15.456: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823869): Gdk-CRITICAL **: 08:47:15.468: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824446): Gdk-CRITICAL **: 08:47:15.472: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824602): Gdk-CRITICAL **: 08:47:15.717: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823902): Gdk-CRITICAL **: 08:47:15.729: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823477): Gdk-CRITICAL **: 08:47:15.733: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823614): Gdk-CRITICAL **: 08:47:15.737: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824030): Gdk-CRITICAL **: 08:47:15.741: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823354): Gdk-CRITICAL **: 08:47:15.745: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823408): Gdk-CRITICAL **: 08:47:15.749: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823678): Gdk-CRITICAL **: 08:47:15.753: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825024): Gdk-CRITICAL **: 08:47:15.757: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824919): Gdk-CRITICAL **: 08:47:15.761: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824327): Gdk-CRITICAL **: 08:47:15.765: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824503): Gdk-CRITICAL **: 08:47:15.769: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3823991): Gdk-CRITICAL **: 08:47:15.515: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824613): Gdk-CRITICAL **: 08:47:15.777: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824354): Gdk-CRITICAL **: 08:47:15.781: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824294): Gdk-CRITICAL **: 08:47:15.785: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824170): Gdk-CRITICAL **: 08:47:15.789: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823381): Gdk-CRITICAL **: 08:47:15.793: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824511): Gdk-CRITICAL **: 08:47:15.574: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824557): Gdk-CRITICAL **: 08:47:15.893: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824831): Gdk-CRITICAL **: 08:47:15.925: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3823921): Gdk-CRITICAL **: 08:47:15.614: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3825005): Gdk-CRITICAL **: 08:47:15.615: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824736): Gdk-CRITICAL **: 08:47:15.629: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824592): Gdk-CRITICAL **: 08:47:15.957: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824567): Gdk-CRITICAL **: 08:47:15.647: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3825156): Gdk-CRITICAL **: 08:47:15.649: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3825192): Gdk-CRITICAL **: 08:47:15.650: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823887): Gdk-CRITICAL **: 08:47:16.049: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824186): Gdk-CRITICAL **: 08:47:16.069: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825117): Gdk-CRITICAL **: 08:47:16.085: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[9786 1992]
......
[9806 1792]
.....
[9783 1850]
...
[1752 9814]
.
[1764 9804]
......................
[1701 9804]
........
[9838 1520]
........
[9825 1503]
.
[9838 1356]
............
[9686 1682]
....
[1885 9576]
..
[2006 9382]
...
[9725 1554]
.
[2336 9009]
.
[9886 1105]
.....
[9742 1322]
.
[9451 1862]
.
[9837 1270]
.
[9476 1722]
.
[9687 1303]
.
[9237 1835]
.
[9290 1751]
.
[9727 1247]
.
[9097 1850]
..
[9617 1345]
.
[9528 1385]
.
[9395 1651]
.
[9641 1159]
.
[3139 8082]
..
[9412 1571]
.
[7613 3679]
.
[9674 1107]
.
[9418 1558]
.
[9765 1160]
.
[9701 1160]
.
[9803 1044]
.
[2891 8289]
..
[9836  996]
.
[8664 2333]
.
[9822  993]
..
[9124 1842]
.
[9789 1067]
.
[8287 2792]
..
[8034 3116]
.
[9023 1889]
.
[8711 2268]
.
[8206 2843]
.
[8204 2879]
...
[8953 1999]
.
[7757 3234]
.
[8442 2510]
....
[6237 4915]
..
[4391 6731]
...
[6794 4340]
..
[3661 7367]
.
[6981 4083]
..
[6888 4137]
.
[5011 6034]
.
[7816 3130]
.
[5256 5815]
..
[7332 3602]
.....
[7936 2960]
.
[6440 4509]
..
[6718 4294]
..
[4362 6681]
..
[4354 6581]
..
[4928 6117]
.....
[7713 3053]
.
[4700 6317]
......
[4965 6069]
...
[4313 6732]
......
[5609 5391]
..
[4412 6569]
...
[6671 4302]
........
[6225 4639]
.........................................................................................................................................................................
Data Dump...
.........................
Data Dump...
..
Data Dump...
.....
Data Dump...
.
Data Dump...
.....................
Data Dump...
.
Data Dump...
....
Data Dump...

Data Dump...
...........
Data Dump...
..................................................................................................................................................................................................................................................................
[5012   33]
.....
[4723   36]
.
[4544  120]
..
[4921    9]
.....
[ 164 4816]
..
[4654   11]
...
[4507  105]
....
[4864    5]
...........
[4562   37]
..
[4525   25]
...
[4603   18]
...
[4505   21]
..
[ 215 4490]
....
[4460   15]
..
[4373   15]
..
[4285   43]
.....
[4256   22]
......
[4151   35]
.......
[4239  118]
.
[4107  190]
..............
[4082   74]
.
[4055  102]
.
[4018   78]
......
[3824   98]
..
[3907  138]
...
[3921  117]
....
[ 389 3925]
..................
[3775   95]
...
[3800   99]
..........
[ 566 3490]
..............
[ 514 3309]
.
[3669  110]
........
[3392  294]
....
[3483  201]
..................
[3306  229]
..
[3046  485]
..
[3128  466]
..
[3152  438]
..........
[2617 1135]
.
[2978  636]
..........
[2946  516]
................
[3053  429]
..
[2711  564]
.....
[1070 2615]
.
[2924  252]
..
[3059  305]
....
[ 916 2490]
..
[2204 1345]
...
[2337 1019]
.
[1327 2198]
.
[2304 1083]
..
[1783 1733]
.
[2216 1004]
...........
[2197 1104]
....
[1081 2393]
......
[1538 1905]
..
[ 991 2618]
.....
[1366 1905]
..
[1391 1984]
.
[1462 1979]
..
[1492 1480]
....
[1733 1535]
...
[1277 2053]
......
[2304  933]
..........
[2131  971]
..................................................................................................................................................................................................................................................................................................
[288  11]
.
[280  28]
.......
[276   5]
..........
[315  18]
...
[288   6]
...
[ 56 447]
..
[259  44]
.......
[283  13]
.......
[271   3]
.....
[269   7]
.
[275   5]
............
[ 61 404]
...........
[251  13]
.
[243   9]
......
[244   9]
.......
[281  11]
....
[252   4]
...
[237  12]
..........................
[219  19]
.
[257  24]
........
[202  49]
.......
[215   9]
.....
[210  31]
.....
[246  18]
....
[234  32]
..
[245  19]
..
[ 87 285]
..............
[104 343]
...........................
[208  16]
..........
[ 70 252]
.....
[200  16]
.............................
[195  49]
............
[211  19]
....
[197  17]
............
[144  59]
..............
[171  27]
......
[192  46]
.........
[147 155]
....
[188  61]
.................
[160  77]
........
[163  46]
.......
[163  46]
....
[123 262]
...
Data Dump...
.
Data Dump...
..........
Data Dump...

Data Dump...

[116 216]
....
[157  20]
........
[145 148]
.
[177  49]
..
[144  93]
.
[156  66]
....
[120 129]
.
Data Dump...
....
[136 218]
...
Data Dump...

[143 125]
...........
Data Dump...
.
[173  32]
....
Data Dump...
...........
[159  92]
.....
Data Dump...
.
[150 156]
.
Data Dump...
....
Data Dump...
..
[ 98 205]
...
Data Dump...
......
[145 116]
.....
Data Dump...
...
[115 114]
....
[114  39]
..
Data Dump...
....
Data Dump...
....
[118 164]
..
[125 256]
.
[130 171]
.
Data Dump...
...
Data Dump...
...........
[112 127]
.....
Data Dump...
..
[139  76]
.......
[162  50]
..........................
Data Dump...
.
Data Dump...
..
Data Dump...

Data Dump...
...
Data Dump...
.
Data Dump...
.
Data Dump...
...
Data Dump...
.......
Data Dump...
..
Data Dump...
................................
Data Dump...
.......
Data Dump...
.
Data Dump...
............................
Data Dump...
...........
Data Dump...
........
Data Dump...
..........
Data Dump...
....
Data Dump...
.
Data Dump...
...
Data Dump...
...
Data Dump...
................
Data Dump...
.
Data Dump...
....
Data Dump...

Data Dump...
...........
Data Dump...
.....
Data Dump...
.
Data Dump...

Data Dump...

Data Dump...

Data Dump...

Data Dump...

Data Dump...
..
Data Dump...
........
Data Dump...
.
Data Dump...
...
Data Dump...
..
Data Dump...
.
Data Dump...
...
Data Dump...
..
Data Dump...

Data Dump...
.
Data Dump...

Data Dump...
.
Data Dump...
.
Data Dump...

Data Dump...
No 1 1
Done
slurmstepd-phcompute025: error: Detected 17 oom-kill event(s) in StepId=824556.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.
