Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823348): Gdk-CRITICAL **: 08:46:56.291: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823889): Gdk-CRITICAL **: 08:46:58.834: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823412): Gdk-CRITICAL **: 08:46:59.136: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824605): Gdk-CRITICAL **: 08:46:59.859: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823762): Gdk-CRITICAL **: 08:47:00.052: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824414): Gdk-CRITICAL **: 08:47:00.176: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825157): Gdk-CRITICAL **: 08:47:00.355: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824128): Gdk-CRITICAL **: 08:47:00.358: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824537): Gdk-CRITICAL **: 08:47:00.421: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825040): Gdk-CRITICAL **: 08:47:00.456: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824160): Gdk-CRITICAL **: 08:47:02.293: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824270): Gdk-CRITICAL **: 08:47:02.338: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824223): Gdk-CRITICAL **: 08:47:05.599: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825060): Gdk-CRITICAL **: 08:47:05.796: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824091): Gdk-CRITICAL **: 08:47:06.459: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824692): Gdk-CRITICAL **: 08:47:06.498: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824999): Gdk-CRITICAL **: 08:47:06.601: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825124): Gdk-CRITICAL **: 08:47:06.622: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823724): Gdk-CRITICAL **: 08:47:06.633: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825176): Gdk-CRITICAL **: 08:47:06.641: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824667): Gdk-CRITICAL **: 08:47:06.652: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3823465): Gdk-CRITICAL **: 08:47:06.661: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824975): Gdk-CRITICAL **: 08:47:06.676: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825093): Gdk-CRITICAL **: 08:47:06.689: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823524): Gdk-CRITICAL **: 08:47:06.709: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823449): Gdk-CRITICAL **: 08:47:06.761: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824157): Gdk-CRITICAL **: 08:47:06.814: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823733): Gdk-CRITICAL **: 08:47:06.857: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824306): Gdk-CRITICAL **: 08:47:07.309: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823628): Gdk-CRITICAL **: 08:47:07.326: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824235): Gdk-CRITICAL **: 08:47:07.477: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3825194): Gdk-CRITICAL **: 08:47:07.485: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824283): Gdk-CRITICAL **: 08:47:07.506: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823999): Gdk-CRITICAL **: 08:47:07.601: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825169): Gdk-CRITICAL **: 08:47:08.143: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824428): Gdk-CRITICAL **: 08:47:08.636: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823365): Gdk-CRITICAL **: 08:47:08.685: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824810): Gdk-CRITICAL **: 08:47:08.752: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3823985): Gdk-CRITICAL **: 08:47:08.764: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824403): Gdk-CRITICAL **: 08:47:08.781: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824444): Gdk-CRITICAL **: 08:47:08.840: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824140): Gdk-CRITICAL **: 08:47:09.653: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823786): Gdk-CRITICAL **: 08:47:10.702: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824829): Gdk-CRITICAL **: 08:47:11.258: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824572): Gdk-CRITICAL **: 08:47:11.328: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824336): Gdk-CRITICAL **: 08:47:11.588: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825020): Gdk-CRITICAL **: 08:47:22.890: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824708): Gdk-CRITICAL **: 08:47:22.930: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824764): Gdk-CRITICAL **: 08:47:22.938: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824661): Gdk-CRITICAL **: 08:47:23.001: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824940): Gdk-CRITICAL **: 08:47:23.005: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824360): Gdk-CRITICAL **: 08:47:23.011: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824983): Gdk-CRITICAL **: 08:47:23.022: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824046): Gdk-CRITICAL **: 08:47:23.047: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824593): Gdk-CRITICAL **: 08:47:23.091: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825113): Gdk-CRITICAL **: 08:47:23.149: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825189): Gdk-CRITICAL **: 08:47:23.157: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824074): Gdk-CRITICAL **: 08:47:23.185: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824578): Gdk-CRITICAL **: 08:47:23.193: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824570): Gdk-CRITICAL **: 08:47:23.196: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824210): Gdk-CRITICAL **: 08:47:23.201: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824399): Gdk-CRITICAL **: 08:47:23.205: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824372): Gdk-CRITICAL **: 08:47:23.209: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824802): Gdk-CRITICAL **: 08:47:23.213: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823992): Gdk-CRITICAL **: 08:47:23.221: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825140): Gdk-CRITICAL **: 08:47:23.225: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824896): Gdk-CRITICAL **: 08:47:23.229: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824194): Gdk-CRITICAL **: 08:47:23.233: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825104): Gdk-CRITICAL **: 08:47:23.237: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823906): Gdk-CRITICAL **: 08:47:23.241: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825164): Gdk-CRITICAL **: 08:47:23.249: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824949): Gdk-CRITICAL **: 08:47:23.257: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3825148): Gdk-CRITICAL **: 08:47:23.261: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824484): Gdk-CRITICAL **: 08:47:23.269: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824991): Gdk-CRITICAL **: 08:47:23.273: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(DataCollector_Deterministic.py:3824635): Gdk-CRITICAL **: 08:47:23.280: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824515): Gdk-CRITICAL **: 08:47:23.285: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824783): Gdk-CRITICAL **: 08:47:23.297: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824819): Gdk-CRITICAL **: 08:47:23.301: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824924): Gdk-CRITICAL **: 08:47:23.306: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823706): Gdk-CRITICAL **: 08:47:25.785: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823664): Gdk-CRITICAL **: 08:47:25.806: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823554): Gdk-CRITICAL **: 08:47:25.817: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823600): Gdk-CRITICAL **: 08:47:25.821: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823801): Gdk-CRITICAL **: 08:47:25.825: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824062): Gdk-CRITICAL **: 08:47:25.853: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823926): Gdk-CRITICAL **: 08:47:25.859: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823660): Gdk-CRITICAL **: 08:47:25.871: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823398): Gdk-CRITICAL **: 08:47:25.877: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823819): Gdk-CRITICAL **: 08:47:25.973: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823430): Gdk-CRITICAL **: 08:47:26.028: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823487): Gdk-CRITICAL **: 08:47:26.033: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823874): Gdk-CRITICAL **: 08:47:26.037: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3824028): Gdk-CRITICAL **: 08:47:26.052: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823615): Gdk-CRITICAL **: 08:47:26.068: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823439): Gdk-CRITICAL **: 08:47:26.072: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823461): Gdk-CRITICAL **: 08:47:26.077: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823380): Gdk-CRITICAL **: 08:47:26.109: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823846): Gdk-CRITICAL **: 08:47:26.137: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3823564): Gdk-CRITICAL **: 08:47:26.297: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Initalising...
Running Sim...
..Initalising...
Running Sim...
.Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
..Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
..Initalising...
Running Sim...
...Initalising...
Running Sim...
..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[1772 8804]
...
[1658 8896]
......
[1711 8867]
.
[1681 8894]
......
[8761 1830]
..
[1719 8900]
.
[1696 8890]
.
[8985 1546]
.
[1698 8835]
...
[8860 1691]
.............
[8822 1727]
........
[9097 1341]
...................
[8912 1507]
..
[2502 8063]
.
[8884 1607]
.
[8589 1953]
.
[9374  961]
.
[8861 1569]
....
[9298 1046]
.
[2488 8086]
...
[8355 2167]
....
[7357 3269]
.
[9064 1324]
..
[9078 1347]
.
[8476 2002]
.
[9119 1178]
.
[8782 1621]
.
[9284 1056]
..
[8370 2091]
.
[9205 1159]
.
[9181 1189]
.
[9283 1060]
..
[9002 1391]
.
[4700 5869]
.
[2782 7803]
.
[9247 1081]
.
[3525 7019]
.
[2937 7677]
.
[3130 7428]
.
[9357  974]
.
[6954 3587]
.
[8004 2412]
.
[8321 2109]
.
[3475 7072]
..
[4891 5720]
..
[3469 7111]
.
[3644 6914]
.
[8494 1865]
.
[6317 4238]
.
[6580 4026]
.
[6468 4049]
.
[3779 6822]
...
[7308 3228]
...
[6447 4089]
.
[5318 5233]
...
[3755 6847]
......
[5611 5004]
..
[7706 2730]
.
[6960 3549]
.
[6339 4202]
.
[5526 5030]
..
[4890 5676]
.
[7385 3065]
.
[6472 4049]
..
[6688 3817]
.
[7884 2509]
.
[4399 6131]
.
[4075 6505]
..
[5983 4568]
.....
[4305 6273]
...
[5225 5244]
.........
[7479 2958]
..
[6414 4063]
......
[7071 3285]
............................................................................................................................................................................................................
Data Dump...
......
Data Dump...
......
Data Dump...
.
Data Dump...

Data Dump...
..
Data Dump...
...
Data Dump...

Data Dump...
...
Data Dump...

Data Dump...
.....
Data Dump...

Data Dump...
......................
Data Dump...
...................................................................................................................................
[3165    6]
........
[3096   15]
............................................................
[3022    5]
............................
[2976    8]
.
[2995   10]
...........
[2916   23]
...............
[2857   65]
.
[2929   14]
...
[2806   65]
.
[2912    7]
............
[2846   48]
......
[2841   27]
..
[2884   14]
........
[2759  182]
....
[2827   10]
................
Data Dump...
..............
[2691   51]
......
[ 282 2773]
........
Data Dump...
......
[2651  147]
....
[2626  162]
........
[ 336 2538]
..
[2646  114]
......................
[ 309 2620]
...............
[2740   40]
....
[2064  744]
....
[2565  108]
..
[2539  115]
......
[ 345 2612]
..............
[ 539 2214]
.....
[ 593 2244]
......
[ 564 2261]
.....
[2429  217]
.......
[ 489 2459]
....
[2505  135]
...
[2256  447]
..
[ 600 2259]
...........
[1893  690]
.
[2345  259]
.
Data Dump...
...
[ 680 2048]
...
[1141 1474]
.
[2088  535]
.
[ 642 2118]
.
[1052 1709]
...
[1822  844]
..
[ 705 2092]
..
[1982  675]
...
[1865  871]
...
[1785  885]
....
[2089  573]
.
[2347  236]
..
[ 880 1862]
....
[1283 1486]
..
[2365  108]
.
[1160 1534]
..
[1785  807]
.....
[2026  599]
.
[1764  836]
.....
[1483 1149]
..
[1383 1392]
.........
[1945  564]
..
Data Dump...
...
[1457 1009]
........
[ 956 1798]
...............
Data Dump...
..................
Data Dump...
..................................
Data Dump...
..................
Data Dump...

Data Dump...
....
Data Dump...
......
Data Dump...
...................
Data Dump...
............
[157  11]

Data Dump...
....
[171  36]

Data Dump...
..............
[149   5]

Data Dump...
.....................................
[ 41 204]

Data Dump...
...........
[128   8]

Data Dump...
..............................
[163  22]

Data Dump...
............
[118  27]

Data Dump...
.....
[ 56 144]

Data Dump...
.................
[ 39 187]

Data Dump...
.......
[116  13]

Data Dump...
.........................
[ 55 197]

Data Dump...
..........
[110  78]

Data Dump...
......................
[151  10]

Data Dump...
.
[144  10]

Data Dump...
....
[128  19]
........
Data Dump...
...
[ 44 102]
...
[ 61 138]
.......
[ 54 158]
.
Data Dump...

Data Dump...
.
Data Dump...
.........
[ 47 174]
..
Data Dump...
.
[100  30]
...
[ 54 174]

Data Dump...
......
Data Dump...
...........
[124  37]
.......
[113  53]
..
[112  14]
.
[ 55 152]
....
Data Dump...

[ 53 130]
..
Data Dump...
.
[ 83 121]
...
Data Dump...

[114  22]
.
[94 81]
.
Data Dump...

[ 60 133]
...
Data Dump...
.
Data Dump...
.
Data Dump...

[83 82]
..
[97 41]
..
Data Dump...

Data Dump...
..
[ 67 133]
..
[100  70]
.
[111  74]
..
[95 54]
..
Data Dump...

Data Dump...
.
Data Dump...

[136  44]
..
[ 85 116]
.
Data Dump...
.
Data Dump...

[120  15]
.
Data Dump...

[87 97]
.
[99 55]
.
Data Dump...

[105  55]
..
Data Dump...

Data Dump...

[110  15]
..
Data Dump...

[ 92 114]
..
Data Dump...

Data Dump...
.
[105  37]
.
Data Dump...

[77 73]
.
Data Dump...

Data Dump...

[105  30]
.
[79 45]
.
[ 69 114]
.
Data Dump...

Data Dump...

Data Dump...

Data Dump...
No 1 6
Done
slurmstepd-phcompute025: error: Detected 19 oom-kill event(s) in StepId=824561.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.
