Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3317910): Gdk-CRITICAL **: 00:59:41.070: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3317838): Gdk-CRITICAL **: 00:59:42.833: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3317829): Gdk-CRITICAL **: 00:59:43.296: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3317864): Gdk-CRITICAL **: 00:59:43.311: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3317809): Gdk-CRITICAL **: 00:59:43.362: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3317777): Gdk-CRITICAL **: 00:59:43.370: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3317885): Gdk-CRITICAL **: 00:59:43.382: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3317771): Gdk-CRITICAL **: 00:59:43.384: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3317795): Gdk-CRITICAL **: 00:59:43.394: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused

(DataCollector_Deterministic.py:3317901): Gdk-CRITICAL **: 00:59:43.409: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Initalising...
Running Sim...

Data Dump...
Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
.Initalising...
Running Sim...
..................................................................................
[4692 9916]
.
[4711 9924]
.
[4727 9931]
.
[4708 9928]
.
[4691 9905]
.
[4714 9918]
.
[4660 9922]
.
[4674 9919]
.
[4651 9921]
..................................................................................
[2229 9842]
.
[2274 9844]
.
[2284 9842]
.
[2268 9830]
.
[2258 9823]
.
[2295 9839]
.
[2269 9830]
.
[2250 9850]
.
[2231 9834]
..................................................................................
[1164 9757]
.
[1154 9765]
.
[1122 9739]
.
[1159 9744]
.
[1160 9753]
.
[1168 9757]
.
[1164 9759]
.
[1114 9780]
.
[1106 9756]
..................................................................................
[ 598 9685]
.
[ 610 9676]
.
[ 577 9660]
.
[ 607 9676]
.
[ 624 9672]
.
[ 594 9674]
.
[ 574 9660]
.
[ 588 9681]
.
[ 600 9694]
..................................................................................
[ 350 9584]
.
[ 346 9598]
.
[ 315 9577]
.
[ 354 9577]
.
[ 340 9578]
.
[ 330 9591]
.
[ 347 9585]
.
[ 330 9610]
.
[ 339 9594]
.................................................................................
[ 228 9505]
.
[ 215 9462]
.
[ 213 9494]
.
[ 183 9409]
.
[ 207 9496]
.
[ 226 9502]
.
[ 204 9493]
..
[ 195 9497]
........
[ 206 9381]
.....................................................................
[ 148 9418]
....
[ 124 9356]
.
[ 143 9196]
..
[ 137 9373]
.
[ 142 9416]
..
[ 117 8717]
...
[ 148 8852]
.
[ 123 9351]
.......................
[ 154 7985]
.............................................
[  97 9283]
.
[  82 8882]
.
[ 108 9103]
...
[  98 9308]
.........
[  79 8960]
.
[ 105 7750]
........................
[  98 6523]
.....
[ 114 6441]
......................
[  75 9102]
........
[  72 8978]
..
[  90 8214]
..........
[  58 7254]
......
[ 138 5074]
......
[  55 7588]
.........................
[  61 8482]
....
[  86 5215]
..........
[  58 7811]
..................
[  72 6119]
.......
[  87 4052]
.........
[  95 3897]
.........
[  55 6502]
....
[  51 4806]
..
[  45 5396]
..................
[  50 5542]
....................
[ 128 2820]
.......
[  77 3134]
.....
[  69 3901]
..........
[  53 4140]
...........................
[  42 3394]
.
[  76 2373]
.
[  47 2909]
..
[  49 3485]
.....
[  89 2236]
....................................
[  64 2379]
.
[  51 2519]
...........
[  75 1855]
...........
[ 121 1591]
..............
[  48 2081]
....
[  39 2065]
....
[  42 1699]
...............
[  69 1415]
............
[  51 1486]
.
[  83 1231]
.........
[  64 1375]
............................
[  70 1114]
..
[  48 1259]
................
[  38 1289]
....
[  41 1002]
.......
[112 899]
....
[ 50 896]
..................
[ 62 863]
.....
[ 60 833]
................
[ 80 683]
......
[ 47 788]
.......................
[ 67 684]
..
[ 49 563]
.
[ 37 780]
......
[ 41 609]
...................
[ 61 563]
....................
[108 542]
.
[ 46 504]
..............
[ 56 503]
....
[ 47 375]
.....................
[ 78 407]
..
[ 36 511]
............
[ 35 385]
..
[ 65 420]
.
[ 56 380]
.............
[ 41 330]
.......
[ 47 257]
.....................................................
[ 54 300]
...
[ 52 264]
.
[105 310]
.
[ 34 338]
.
[ 45 174]
..
[ 41 228]
..............
[ 32 237]
.........
[ 63 269]
....
[ 72 244]
.....................
[ 43 138]
..................
[ 40 164]
....
[ 50 192]
....................
[ 42 112]
....
[ 33 232]
..............................
[ 32 163]
..
[ 41 101]
..
[ 52 202]
..
[ 39 118]
..................
[ 49 145]
.....
[ 62 182]
....
[ 97 208]
..................
[ 71 168]
.
[ 39 101]
................
[ 32 162]
.............
[ 48 110]
....
[39 91]
..................
[ 32 122]
..........
[39 86]
....../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
..........
[ 48 137]
...
[46 90]
........
[ 59 132]
......
[ 31 129]
.................
[44 84]
...........
[ 95 131]
.....
[ 65 111]
.....
[31 87]
.......
[42 78]
................../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
..
[ 30 105]
................
[ 39 106]
.
[59 97]
.................
[30 68]
..
[30 88]
.......................
[63 78]
...........
[93 77]
..
[30 75]
..........
[30 60]
..
[56 73]
..........
[37 74]
.......
[30 65]
..........................
[30 59]
........
[29 50]
.............
[30 56]
..../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
...
[59 61]
...
[54 59]
...............
[27 44]
..
[35 55]
.
[89 51]
.........................
[26 38]
.......
[50 45]
................
[55 43]
...
[26 36]
............
[35 39]
.........
[26 34]
.................
[45 35]
.
[26 34]
..
[87 40]
....../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.....................
[51 33]
..
[35 35]
.
[40 31]
............................
[40 29]
.
[84 31]
.........
[32 25]
.......
[50 29]
.........
[40 26]
.......................
[39 24]
....
[32 21]
...........
[83 22]
.......
[39 23]
..
[48 23]
..................
[39 21]
........
[32 20]
..........
[39 21]
......./home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.............
[46 21]
...
[78 17]
.
[29 18]
.....................
[27 18]
.......
[45 18]
.............
[27 16]
..
[76 13]
..................
[27 16]
...
[43 18]
................
[27 16]
................
[27 15]
.
[76 11]
.....
[41 15]
...........
[27 15]
...............
[27 15]
../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.......
[41 14]
.......
[70 11]
........
[40 14]
...............
[39 12]
.......
[70 11]
........
[39 12]
..............
[38 12]
.............
[37 12]
.
[68 10]
............
[37 12]
.............
[37 12]
............
[37 12]
....../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

Data Dump...
.
[67 10]
..........
[65 10]
..........
[64 10]
..........
[63  9]
..........
[62  9]
..........
[58  9]
..........
[56  9]
..........
[54  9]
..........
[54  9]
..........
[54  9]
..........
[54  9]
..........
[54  9]
..........
[54  9]
..........
[54  9]
........../home/s1932078/Documents/MPhys_Project/SRI/src/data_extraction/DataCollector_Deterministic.py:120: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig(os.path.join(data_output_path, f'InfectionsVsTimePlot_{name_suffix}.png'))

[54  9]

Data Dump...
High 1 1
Done
slurmstepd-phcompute025: error: Detected 1 oom-kill event(s) in StepId=810620.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.
